#!/bin/bash

if [ ! $GLAST_EXT ]
then
    echo -n "What is the location of the external libraries? "
    read GLAST_EXT
    export GLAST_EXT
fi

export INST_DIR=`dirname $0`/../

if [ ! $GLAST_EXT ] || [ ! $INST_DIR ]
then
   echo "External libraries or script location not set"
   exit 1
fi

if [ `echo $PFILES|sed -n -e '/;/p'` ]
then
  SEPARATOR=":"
else
  SEPARATOR=";"
fi

if [ ! $PFILES ]
then
  export PFILES="$HOME/pfiles"
  mkdir -p $PFILES
fi
CMTROOT="/afs/slac/g/glast/applications/CMT/v1r18p20061003"; export CMTROOT
CMTCONFIG=rh9_gcc32opt; export CMTCONFIG
ST_APPROOT="${INST_DIR}//st_app/v2"; export ST_APPROOT
ST_GRAPHROOT="${INST_DIR}//st_graph/v1r7"; export ST_GRAPHROOT
HOOPSROOT="${INST_DIR}//hoops/v0r4p5"; export HOOPSROOT
CATALOGACCESSROOT="${INST_DIR}//catalogAccess/v0r3"; export CATALOGACCESSROOT
ST_FACILITIESROOT="${INST_DIR}//st_facilities/v0r12"; export ST_FACILITIESROOT
ASTROROOT="${INST_DIR}//astro/v2r10"; export ASTROROOT
TIPROOT="${INST_DIR}//tip/v2r12"; export TIPROOT
ST_STREAMROOT="${INST_DIR}//st_stream/v0r5"; export ST_STREAMROOT
STPOLICYROOT="${INST_DIR}//STpolicy/v1r3"; export STPOLICYROOT
FACILITIESROOT="${INST_DIR}//facilities/v2r14"; export FACILITIESROOT
F2CROOT="${INST_DIR}//f2c/v2r2"; export F2CROOT
ROOTCINTPOLICYROOT="${INST_DIR}//GlastPolicy/RootcintPolicy/v6r1p3"; export ROOTCINTPOLICYROOT
GLASTPOLICYROOT="${INST_DIR}//GlastPolicy/v6r12p4"; export GLASTPOLICYROOT
GLASTPATTERNPOLICYROOT="${INST_DIR}//GlastPolicy/GlastPatternPolicy/v1r3p3"; export GLASTPATTERNPOLICYROOT
GLASTCPPPOLICYROOT="${INST_DIR}//GlastPolicy/GlastCppPolicy/v1r7p2"; export GLASTCPPPOLICYROOT
PILROOT="${INST_DIR}//IExternal/pil/v1r201p1"; export PILROOT
CFITSIOROOT="${INST_DIR}//IExternal/cfitsio/v1r3006"; export CFITSIOROOT
EXTERNALLIBSROOT="${INST_DIR}//IExternal/ExternalLibs/v5r0"; export EXTERNALLIBSROOT
CLHEPROOT="${INST_DIR}//IExternal/CLHEP/v3r0"; export CLHEPROOT
EXTFILESROOT="${INST_DIR}//IExternal/extFiles/v0r5"; export EXTFILESROOT
ROOTROOT="${INST_DIR}//IExternal/ROOT/v5r14p2"; export ROOTROOT
CPPUNITROOT="${INST_DIR}//IExternal/cppunit/v2r0p1"; export CPPUNITROOT
SOURCEIDENTIFYROOT="${INST_DIR}//sourceIdentify/v1r0p4"; export SOURCEIDENTIFYROOT
CMTPATH="/a/sulky36/g.glast.u30/builds/rh9_gcc32opt/ScienceTools/ScienceTools-v9r1p1"; export CMTPATH
PATH="${GLAST_EXT}//ROOT/v5.14.00d/root/bin:/afs/slac/g/glast/applications/CMT/v1r18p20061003/Linux:/afs/slac/package/lsf/curr/bin:/usr/local/bin:/bin:/usr/bin:/usr/etc:/usr/afsws/bin:/usr/afsws/etc:/usr/bin/X11:/u/gl/glastrm/installbuilder-4.1.0/bin/"; export PATH
CLASSPATH="/afs/slac/g/glast/applications/CMT/v1r18p20061003/java"; export CLASSPATH
unset include
unset lib
NEWCMTCONFIG="i686-rhel39-gcc323"; export NEWCMTCONFIG
BINDIR="rh9_gcc32opt"; export BINDIR
TMP="/tmp"; export TMP
LD_LIBRARY_PATH="${GLAST_EXT}//cppunit/1.10.2/lib:${GLAST_EXT}//ROOT/v5.14.00d/root/bin:${GLAST_EXT}//ROOT/v5.14.00d/root/lib:${GLAST_EXT}//CLHEP/1.9.2.2/lib:${GLAST_EXT}//cfitsio/v3006/lib:/afs/slac/package/lsf/curr/lib:${INST_DIR}//lib/"; export LD_LIBRARY_PATH
EXTFILESSYS="${GLAST_EXT}//extFiles/v0r5"; export EXTFILESSYS
ROOTSYS="${GLAST_EXT}//ROOT/v5.14.00d/root"; export ROOTSYS
unset DYLD_LIBRARY_PATH
STTEST="sttest"; export STTEST
PFILES="${PFILES}${SEPARATOR}${INST_DIR}//pfiles"; export PFILES
ST_apps="gtsrcid=${INST_DIR}//../rh9_gcc32/gtsrcid.exe"; export ST_apps

${INST_DIR}../rh9_gcc32/gtsrcid.exe "$@"
