#!/bin/bash

if [ ! $GLAST_EXT ]
then
    echo -n "What is the location of the external libraries? "
    read GLAST_EXT
    export GLAST_EXT
fi

export INST_DIR=`dirname $0`/../

if [ ! $GLAST_EXT ] || [ ! $INST_DIR ]
then
   echo "External libraries or script location not set"
   exit 1
fi

if [ `echo $PFILES|sed -n -e '/;/p'` ]
then
  SEPARATOR=":"
else
  SEPARATOR=";"
fi

if [ ! $PFILES ]
then
  export PFILES="$HOME/pfiles"
  mkdir -p $PFILES
fi

GLAST_DIR=`which test_st_facilities|sed 's/test_st_facilities/../'`
ROOT="v5.16.00-gl1"

export LD_LIBRARY_PATH="${GLAST_EXT}//cppunit/1.10.2/lib:${GLAST_EXT}//ROOT/${ROOT}/root/lib:${GLAST_EXT}//CLHEP/1.9.2.2/lib:${GLAST_EXT}//cfitsio/v3060/lib:${GLAST_DIR}//lib/:"
export ROOTSYS="${GLAST_EXT}//ROOT/${ROOT}/root"

ST_apps="gtsrcid=${INST_DIR}//../rh9_gcc32/gtsrcid.exe"; export ST_apps

${INST_DIR}../rh9_gcc32/gtsrcid.exe "$@"
