CMT_tag=$(tag)
CMTROOT=/opt/projects/glast/extlib/CMT/v1r16p20040701
CMT_root=/opt/projects/glast/extlib/CMT/v1r16p20040701
CMTVERSION=v1r16p20040701
CMTrelease=15
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/knodlseder/glast/src/InstallArea/rh9_gcc32/bin:/opt/projects/glast/extlib/CMT/v1r16p20040701/${CMTBIN}:.:/opt/projects/gri/v1.0/Linux_i686/bin:/opt/projects/integral/cesr/bin:/opt/projects/integral/osa/v5.0/bin:/opt/common/root/v4.03.02/bin:/opt/common/lheasoft/v5.3.1/i686-pc-linux-gnu-libc2.1/scripts:/opt/common/lheasoft/v5.3.1/i686-pc-linux-gnu-libc2.1/bin:.:/opt/projects/gri/v1.0/Linux_i686/bin:/opt/projects/integral/cesr/bin:/opt/projects/integral/osa/v5.0/bin:/opt/common/root/v4.03.02/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/projects/glast/bin:/opt/projects/glast/installer:/home/knodlseder/glast/bin:/sbin:/home/knodlseder/bin:/opt/projects/glast/bin:/opt/projects/glast/installer:/opt/projects/glast/bin:/opt/projects/glast/installer:/opt/projects/glast/bin:/opt/projects/glast/installer:/home/knodlseder/glast/bin:/sbin:${ROOTSYS}/bin
CLASSPATH=/home/knodlseder/glast/src/InstallArea/share/bin:/home/knodlseder/glast/src/InstallArea/share/lib:/opt/projects/glast/extlib/CMT/v1r16p20040701/java
debug_option=-g
cc=gcc
cdebugflags=$(debug_option)
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppdebugflags=$(debug_option)
cppflags=-pipe -ansi -W -Wall  -fPIC -shared -D_GNU_SOURCE -Dlinux -Dunix 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppoptions) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic  $(linkdebug)
cpplink=$(cpp)   $(cpplinkflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -s 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-rh9-gcc32
sourceIdentify_tag=$(tag)
SOURCEIDENTIFYROOT=/home/knodlseder/glast/src/sourceIdentify/v0r1
sourceIdentify_root=/home/knodlseder/glast/src/sourceIdentify/v0r1
SOURCEIDENTIFYVERSION=v0r1
sourceIdentify_cmtpath=/home/knodlseder/glast/src
sourceIdentify_project=Project2
STpolicy_tag=$(tag)
STPOLICYROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/STpolicy/v1r0p6
STpolicy_root=/opt/projects/glast/ScienceTools/LATEST1.1029/STpolicy/v1r0p6
STPOLICYVERSION=v1r0p6
STpolicy_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
STpolicy_project=Project1
GlastPolicy_tag=$(tag)
GLASTPOLICYROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/v6r4
GlastPolicy_root=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/v6r4
GLASTPOLICYVERSION=v6r4
GlastPolicy_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
GlastPolicy_project=Project1
GlastPatternPolicy_tag=$(tag)
GLASTPATTERNPOLICYROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/GlastPatternPolicy/v0r1
GlastPatternPolicy_root=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/GlastPatternPolicy/v0r1
GLASTPATTERNPOLICYVERSION=v0r1
GlastPatternPolicy_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
GlastPatternPolicy_offset=GlastPolicy
GlastPatternPolicy_project=Project1
GlastMain=${GLASTPOLICYROOT}/src/GlastMain.cxx
TestGlastMain=${GLASTPOLICYROOT}/src/TestGlastMain.cxx
GlastCppPolicy_tag=$(tag)
GLASTCPPPOLICYROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/GlastCppPolicy/v0r2p3
GlastCppPolicy_root=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/GlastCppPolicy/v0r2p3
GLASTCPPPOLICYVERSION=v0r2p3
GlastCppPolicy_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
GlastCppPolicy_offset=GlastPolicy
GlastCppPolicy_project=Project1
BINDIR=rh9_gcc32
cppoptions=$(cppdebugflags_s)
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
linkdebug=-g 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC  -ldl 
libraryshr_linkopts=-fPIC -ldl 
TMP=/tmp
hoops_tag=$(tag)
HOOPSROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/hoops/v0r4p4
hoops_root=/opt/projects/glast/ScienceTools/LATEST1.1029/hoops/v0r4p4
HOOPSVERSION=v0r4p4
hoops_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
hoops_project=Project1
pil_tag=$(tag)
PILROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/pil/v1r198
pil_root=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/pil/v1r198
PILVERSION=v1r198
pil_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
pil_offset=IExternal
pil_project=Project1
pil_native_version=1.9.8
pil_DIR=${GLAST_EXT}/pil/$(pil_native_version)
pil_linkopts=-L $(pil_DIR)/lib -lpil -ltermcap -lreadline
hoopsDir=${HOOPSROOT}/${BINDIR}
hoops_linkopts=-L${hoops_root}/${BINDIR} -lhoopsLib 
hoops_stamps=${HOOPSROOT}/${BINDIR}/hoopsLib.stamp 
st_facilities_tag=$(tag)
ST_FACILITIESROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/st_facilities/v0r4p3
st_facilities_root=/opt/projects/glast/ScienceTools/LATEST1.1029/st_facilities/v0r4p3
ST_FACILITIESVERSION=v0r4p3
st_facilities_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
st_facilities_project=Project1
f2c_tag=$(tag)
F2CROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/f2c/v2r2
f2c_root=/opt/projects/glast/ScienceTools/LATEST1.1029/f2c/v2r2
F2CVERSION=v2r2
f2c_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
f2c_project=Project1
f2c_linkopts= -lg2c 
tip_tag=$(tag)
TIPROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/tip/v2r5p0
tip_root=/opt/projects/glast/ScienceTools/LATEST1.1029/tip/v2r5p0
TIPVERSION=v2r5p0
tip_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
tip_project=Project1
ROOT_tag=$(tag)
ROOTROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/ROOT/v3r40200p4
ROOT_root=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/ROOT/v3r40200p4
ROOTVERSION=v3r40200p4
ROOT_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
ROOT_offset=IExternal
ROOT_project=Project1
ROOT_DIR=${GLAST_EXT}/ROOT
ROOT_native_version=v4.02.00
ROOT_PATH=${ROOT_DIR}/$(ROOT_native_version)/root
ROOTSYS=/opt/projects/glast/extlib/ROOT/v4.02.00/root
dict=../dict/
rootcint=rootcint
ROOT_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lTree -lMatrix -lPhysics -lpthread -lm -ldl -rdynamic
ROOT_GUI_libs=-L$(ROOT_PATH)/lib -lHist -lGraf -lGraf3d -lGpad -lRint -lPostscript -lTreePlayer 
ROOT_linkopts=$(ROOT_libs)
ROOT_cppflagsEx=$(ppcmd) "$(ROOT_PATH)/include" -DUSE_ROOT
ROOT_cppflags=-fpermissive
LD_LIBRARY_PATH=/home/knodlseder/glast/src/InstallArea/rh9_gcc32/lib:/opt/projects/gri/v1.0/Linux_i686/lib:/opt/common/root/v4.03.02/lib:/opt/common/lheasoft/v5.3.1/i686-pc-linux-gnu-libc2.1/lib:/opt/projects/gri/v1.0/Linux_i686/lib:/opt/common/root/v4.03.02/lib:/opt/projects/glast/lib:/opt/projects/glast/extlib/cfitsio/v2470/lib:/opt/projects/glast/lib:/opt/projects/glast/extlib/cfitsio/v2470/lib:/opt/projects/glast/lib:/opt/projects/glast/extlib/cfitsio/v2470/lib:/opt/projects/glast/lib:/opt/projects/glast/extlib/cfitsio/v2470/lib:/opt/projects/glast/extlib/ROOT/v4.02.00/root/bin:/opt/projects/glast/extlib/ROOT/v4.02.00/root/lib:/opt/projects/glast/ScienceTools/LATEST1.1029/st_graph/v1r3p2/${BINDIR}
cfitsio_tag=$(tag)
CFITSIOROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/cfitsio/v1r2470p5
cfitsio_root=/opt/projects/glast/ScienceTools/LATEST1.1029/IExternal/cfitsio/v1r2470p5
CFITSIOVERSION=v1r2470p5
cfitsio_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
cfitsio_offset=IExternal
cfitsio_project=Project1
cfitsio_native_version=v2470
cfitsio_DIR=${GLAST_EXT}/cfitsio/$(cfitsio_native_version)
cfitsio_libs=-L${cfitsio_DIR}/lib -lcfitsio 
cfitsio_linkopts=$(cfitsio_libs) 
tip_linkopts=-lHist -L${tip_root}/${BINDIR} -ltipLib 
tipDir=${TIPROOT}/${BINDIR}
tip_stamps=${TIPROOT}/${BINDIR}/tipLib.stamp 
facilities_tag=$(tag)
FACILITIESROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/facilities/v2r12
facilities_root=/opt/projects/glast/ScienceTools/LATEST1.1029/facilities/v2r12
FACILITIESVERSION=v2r12
facilities_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
facilities_project=Project1
facilities_linkopts=-L${facilities_root}/${BINDIR} -lfacilities 
st_facilitiesDir=${ST_FACILITIESROOT}/${BINDIR}
st_facilities_linkopts=-L${st_facilities_root}/${BINDIR} -lst_facilitiesLib 
st_facilities_stamps=${ST_FACILITIESROOT}/${BINDIR}/st_facilitiesLib.stamp 
STTEST=sttest
st_app_tag=$(tag)
ST_APPROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/st_app/v1r6p4
st_app_root=/opt/projects/glast/ScienceTools/LATEST1.1029/st_app/v1r6p4
ST_APPVERSION=v1r6p4
st_app_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
st_app_project=Project1
st_graph_tag=$(tag)
ST_GRAPHROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/st_graph/v1r3p2
st_graph_root=/opt/projects/glast/ScienceTools/LATEST1.1029/st_graph/v1r3p2
ST_GRAPHVERSION=v1r3p2
st_graph_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
st_graph_project=Project1
RootcintPolicy_tag=$(tag)
ROOTCINTPOLICYROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/RootcintPolicy/v5r0p2
RootcintPolicy_root=/opt/projects/glast/ScienceTools/LATEST1.1029/GlastPolicy/RootcintPolicy/v5r0p2
ROOTCINTPOLICYVERSION=v5r0p2
RootcintPolicy_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
RootcintPolicy_offset=GlastPolicy
RootcintPolicy_project=Project1
st_stream_tag=$(tag)
ST_STREAMROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/st_stream/v0r3p0
st_stream_root=/opt/projects/glast/ScienceTools/LATEST1.1029/st_stream/v0r3p0
ST_STREAMVERSION=v0r3p0
st_stream_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
st_stream_project=Project1
st_streamDir=${ST_STREAMROOT}/${BINDIR}
st_stream_linkopts=-L${st_stream_root}/${BINDIR} -lst_streamLib 
st_stream_stamps=${ST_STREAMROOT}/${BINDIR}/st_streamLib.stamp 
st_graph_linkopts=-L${st_graph_root}/${BINDIR} -lst_graph ${st_graph_libs}
root_packages_import=-import=st_graph 
root_packages_include=$(ppcmd)"$(st_graph_root)" 
st_graph_libs=-L$(ROOT_PATH)/lib -lCore -lCint -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lGui -ldl 
st_appDir=${ST_APPROOT}/${BINDIR}
st_app_linkopts=-L${st_app_root}/${BINDIR} -lst_appLib 
st_app_stamps=${ST_APPROOT}/${BINDIR}/st_appLib.stamp 
PFILES=/home/knodlseder/pfiles:/opt/common/lheasoft/v5.3.1/i686-pc-linux-gnu-libc2.1/syspfiles:/home/knodlseder/pfiles:/opt/projects/integral/cesr/pfiles:/opt/projects/integral/osa/v5.0/pfiles:/opt/projects/integral/cesr/pfiles:/opt/projects/integral/osa/v5.0/pfiles:/opt/projects/glast/ScienceTools/LATEST1.1029/st_app/v1r6p4/pfiles:/home/knodlseder/glast/src/sourceIdentify/v0r1/pfiles
catalogAccess_tag=$(tag)
CATALOGACCESSROOT=/opt/projects/glast/ScienceTools/LATEST1.1029/catalogAccess/v0r2p3
catalogAccess_root=/opt/projects/glast/ScienceTools/LATEST1.1029/catalogAccess/v0r2p3
CATALOGACCESSVERSION=v0r2p3
catalogAccess_cmtpath=/opt/projects/glast/ScienceTools/LATEST1.1029
catalogAccess_project=Project1
catalogAccessDir=${CATALOGACCESSROOT}/${BINDIR}
catalogAccess_linkopts=-L${catalogAccess_root}/${BINDIR} -lcatalogAccessLib 
catalogAccess_stamps=${CATALOGACCESSROOT}/${BINDIR}/catalogAccessLib.stamp 
gtsrcidstamps=gtsrcid.stamp
ST_apps=gtsrcid=/home/knodlseder/glast/src/sourceIdentify/v0r1/${BINDIR}/gtsrcid.exe
GlastPatternPolicyDir=${GLASTPATTERNPOLICYROOT}/${BINDIR}
GlastPolicyDir=${GLASTPOLICYROOT}/${BINDIR}
STpolicyDir=${STPOLICYROOT}/${BINDIR}
f2cDir=${F2CROOT}/${BINDIR}
facilitiesDir=${FACILITIESROOT}/${BINDIR}
RootcintPolicyDir=${ROOTCINTPOLICYROOT}/${BINDIR}
st_graphDir=${ST_GRAPHROOT}/${BINDIR}
sourceIdentifyDir=${SOURCEIDENTIFYROOT}/${BINDIR}
CMTINSTALLAREA=/home/knodlseder/glast/src/InstallArea
tag=rh9_gcc32
package=sourceIdentify
version=v0r1
PACKAGE_ROOT=$(SOURCEIDENTIFYROOT)
srcdir=../src
bin=../$(sourceIdentify_tag)/
javabin=../classes/
mgrdir=cmt
project=Project2
use_requirements=requirements $(CMTROOT)/mgr/requirements $(ST_APPROOT)/cmt/requirements $(HOOPSROOT)/cmt/requirements $(CATALOGACCESSROOT)/cmt/requirements $(ST_FACILITIESROOT)/cmt/requirements $(TIPROOT)/cmt/requirements $(ST_GRAPHROOT)/cmt/requirements $(ST_STREAMROOT)/cmt/requirements $(STPOLICYROOT)/cmt/requirements $(F2CROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(ROOTCINTPOLICYROOT)/cmt/requirements $(GLASTPOLICYROOT)/cmt/requirements $(GLASTPATTERNPOLICYROOT)/cmt/requirements $(GLASTCPPPOLICYROOT)/cmt/requirements $(PILROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(CFITSIOROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(ST_APPROOT)" $(ppcmd)"$(HOOPSROOT)" $(ppcmd)"$(CATALOGACCESSROOT)" $(ppcmd)"$(ST_FACILITIESROOT)" $(ppcmd)"$(TIPROOT)" $(ppcmd)"$(ST_GRAPHROOT)" $(ppcmd)"$(ST_STREAMROOT)" $(ppcmd)"$(F2CROOT)" $(ppcmd)"$(FACILITIESROOT)" $(ppcmd)"$(pil_DIR)/include" $(ppcmd)"$(ROOT_PATH)/include" $(ppcmd)"${cfitsio_DIR}/include" 
use_fincludes= $(use_includes)
use_stamps= $(sourceIdentify_stamps)  $(st_app_stamps)  $(hoops_stamps)  $(catalogAccess_stamps)  $(st_facilities_stamps)  $(tip_stamps)  $(st_graph_stamps)  $(st_stream_stamps)  $(STpolicy_stamps)  $(f2c_stamps)  $(facilities_stamps)  $(RootcintPolicy_stamps)  $(GlastPolicy_stamps)  $(GlastPatternPolicy_stamps)  $(GlastCppPolicy_stamps)  $(pil_stamps)  $(ROOT_stamps)  $(cfitsio_stamps) 
use_cflags=  $(sourceIdentify_cflags)  $(st_app_cflags)  $(hoops_cflags)  $(catalogAccess_cflags)  $(st_facilities_cflags)  $(tip_cflags)  $(st_graph_cflags)  $(st_stream_cflags)  $(STpolicy_cflags)  $(f2c_cflags)  $(facilities_cflags)  $(RootcintPolicy_cflags)  $(GlastPolicy_cflags)  $(pil_cflags)  $(ROOT_cflags)  $(cfitsio_cflags) 
use_pp_cflags=  $(sourceIdentify_pp_cflags)  $(st_app_pp_cflags)  $(hoops_pp_cflags)  $(catalogAccess_pp_cflags)  $(st_facilities_pp_cflags)  $(tip_pp_cflags)  $(st_graph_pp_cflags)  $(st_stream_pp_cflags)  $(STpolicy_pp_cflags)  $(f2c_pp_cflags)  $(facilities_pp_cflags)  $(RootcintPolicy_pp_cflags)  $(GlastPolicy_pp_cflags)  $(pil_pp_cflags)  $(ROOT_pp_cflags)  $(cfitsio_pp_cflags) 
use_cppflags=  $(sourceIdentify_cppflags)  $(st_app_cppflags)  $(hoops_cppflags)  $(catalogAccess_cppflags)  $(st_facilities_cppflags)  $(tip_cppflags)  $(st_graph_cppflags)  $(st_stream_cppflags)  $(STpolicy_cppflags)  $(f2c_cppflags)  $(facilities_cppflags)  $(RootcintPolicy_cppflags)  $(GlastPolicy_cppflags)  $(pil_cppflags)  $(ROOT_cppflags)  $(cfitsio_cppflags) 
use_pp_cppflags=  $(sourceIdentify_pp_cppflags)  $(st_app_pp_cppflags)  $(hoops_pp_cppflags)  $(catalogAccess_pp_cppflags)  $(st_facilities_pp_cppflags)  $(tip_pp_cppflags)  $(st_graph_pp_cppflags)  $(st_stream_pp_cppflags)  $(STpolicy_pp_cppflags)  $(f2c_pp_cppflags)  $(facilities_pp_cppflags)  $(RootcintPolicy_pp_cppflags)  $(GlastPolicy_pp_cppflags)  $(pil_pp_cppflags)  $(ROOT_pp_cppflags)  $(cfitsio_pp_cppflags) 
use_fflags=  $(sourceIdentify_fflags)  $(st_app_fflags)  $(hoops_fflags)  $(catalogAccess_fflags)  $(st_facilities_fflags)  $(tip_fflags)  $(st_graph_fflags)  $(st_stream_fflags)  $(STpolicy_fflags)  $(f2c_fflags)  $(facilities_fflags)  $(RootcintPolicy_fflags)  $(GlastPolicy_fflags)  $(pil_fflags)  $(ROOT_fflags)  $(cfitsio_fflags) 
use_pp_fflags=  $(sourceIdentify_pp_fflags)  $(st_app_pp_fflags)  $(hoops_pp_fflags)  $(catalogAccess_pp_fflags)  $(st_facilities_pp_fflags)  $(tip_pp_fflags)  $(st_graph_pp_fflags)  $(st_stream_pp_fflags)  $(STpolicy_pp_fflags)  $(f2c_pp_fflags)  $(facilities_pp_fflags)  $(RootcintPolicy_pp_fflags)  $(GlastPolicy_pp_fflags)  $(pil_pp_fflags)  $(ROOT_pp_fflags)  $(cfitsio_pp_fflags) 
use_linkopts= $(cmt_installarea_linkopts)   $(sourceIdentify_linkopts)  $(st_app_linkopts)  $(hoops_linkopts)  $(catalogAccess_linkopts)  $(st_facilities_linkopts)  $(tip_linkopts)  $(st_graph_linkopts)  $(st_stream_linkopts)  $(STpolicy_linkopts)  $(f2c_linkopts)  $(facilities_linkopts)  $(RootcintPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(cfitsio_linkopts) 
use_libraries= $(st_app_libraries)  $(hoops_libraries)  $(catalogAccess_libraries)  $(st_facilities_libraries)  $(tip_libraries)  $(st_graph_libraries)  $(st_stream_libraries)  $(STpolicy_libraries)  $(f2c_libraries)  $(facilities_libraries)  $(RootcintPolicy_libraries)  $(GlastPolicy_libraries)  $(GlastPatternPolicy_libraries)  $(GlastCppPolicy_libraries)  $(pil_libraries)  $(ROOT_libraries)  $(cfitsio_libraries) 
includes= $(use_includes)
fincludes= $(includes)
gtsrcid_use_linkopts=  $(sourceIdentify_linkopts)  $(st_app_linkopts)  $(hoops_linkopts)  $(catalogAccess_linkopts)  $(st_facilities_linkopts)  $(tip_linkopts)  $(st_graph_linkopts)  $(st_stream_linkopts)  $(STpolicy_linkopts)  $(f2c_linkopts)  $(facilities_linkopts)  $(RootcintPolicy_linkopts)  $(GlastPolicy_linkopts)  $(pil_linkopts)  $(ROOT_linkopts)  $(cfitsio_linkopts) 
constituents= gtsrcid 
all_constituents= $(constituents)
constituentsclean= gtsrcidclean 
all_constituentsclean= $(constituentsclean)
cmt_installarea_paths=$(cmt_installarea_prefix)/$(tag)/bin $(cmt_installarea_prefix)/$(tag)/lib $(cmt_installarea_prefix)/share/lib $(cmt_installarea_prefix)/share/bin
Project2_installarea_prefix=$(cmt_installarea_prefix)
Project2_installarea_prefix_remove=$(Project2_installarea_prefix)
cmt_installarea_linkopts= -L/home/knodlseder/glast/src/$(Project2_installarea_prefix)/$(tag)/lib 
